/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ChiTieuBLL;
import BLL.GioiHanChiTieuBLL;
import BLL.TieuDungBLL;
import DTO.ChiTieuDTO;
import DTO.GioiHanChiTieuDTO;
import DTO.TieuDungDTO;
import Utils.DBUtils;
import java.sql.*;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huynh
 */
public class ThongKeChiTieuUI extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeChiTieuUI
     */
    public String tenDangNhap;
    public ThongKeChiTieuUI() {
        initComponents();
        tenDangNhap = "admin";
        this.jLabel2.setText("<html><body>Ngày sử dụng<br>nhiều nhất</body></html>");
        this.loadThangThongKe(tenDangNhap);
        this.updateLuongTienChiTieu();
        this.loadTableChiTieu();
        this.loadTableTieuDung();
        
    }
    public ThongKeChiTieuUI(String nguoiDung){
        tenDangNhap = nguoiDung;
        initComponents();
        this.jLabel2.setText("<html><body>Ngày sử dụng<br>nhiều nhất</body></html>");
        this.loadThangThongKe(tenDangNhap);
        this.updateLuongTienChiTieu();
        this.loadTableChiTieu();
        this.loadTableTieuDung();
    }
    public DefaultTableModel tblModelChiTieu;
    public void loadTableChiTieu(){
        tblModelChiTieu = new DefaultTableModel();
        String tieude[] ={"Mã giao dịch", "Ngày giao dịch", "Lượng tiền"};
        tblModelChiTieu.setColumnIdentifiers(tieude);
    }
    
    public DefaultTableModel tblModelTieuDung;
    public void loadTableTieuDung(){
        tblModelTieuDung = new DefaultTableModel();
        String tieude[] = {"STT", "Tên tiêu dùng", "Số lượng", "Thành tiền"};
        tblModelTieuDung.setColumnIdentifiers(tieude);
    }

    public ArrayList<String>arrThangThongKe = new ArrayList<String>();
    public void loadThangThongKe(String nguoiDung){
        try{
            String strSQL = "select ngaychi from thongtinchitieu where tendangnhap = '"+nguoiDung+"' order by ngaychi desc";
            Connection con = new DBUtils().createConn();
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(strSQL);
            while(rs.next()){
                String[] row = rs.getDate("ngaychi").toString().split("-");
                String temp = row[1]+"/"+row[0];
                if(!arrThangThongKe.contains(temp))
                    arrThangThongKe.add(temp);
            }
            cbbThang.setModel(new DefaultComboBoxModel<String>(arrThangThongKe.toArray(new String[0])));
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public String dinhDangTienTe(double soTien){
        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);
        String str = en.format(soTien);
        return str;
    }
    
    ArrayList<ChiTieuDTO> arrChiTieuThang = new ArrayList<ChiTieuDTO>();
    public void updateLuongTienChiTieu(){
        ChiTieuBLL chiTieuBll = new ChiTieuBLL();
        arrChiTieuThang = chiTieuBll.getAllChiTieuByUser(tenDangNhap);
        
        ChiTieuDTO chitieu = new ChiTieuDTO();
        ArrayList<String> arrMaChiTieu = new ArrayList<String>();
        for(int i=0; i<arrChiTieuThang.size();i++){
            chitieu = arrChiTieuThang.get(i);
            if(!arrMaChiTieu.contains(chitieu.getMaChiTieu())){
                String machitieu = chitieu.getMaChiTieu();
                arrMaChiTieu.add(machitieu);
                chiTieuBll.updateLuongTienById(machitieu);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpanel = new javax.swing.JTabbedPane();
        panelChiTieu = new javax.swing.JPanel();
        btnQuayLai1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCachHanMuc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTieu = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btnChiTiet = new javax.swing.JButton();
        dateNgaySDNhieuNhat = new com.toedter.calendar.JDateChooser();
        cbbThang = new javax.swing.JComboBox<>();
        panelTieuDung = new javax.swing.JPanel();
        btnQuayLai2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTieuDung = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabpanel.setEnabled(false);

        btnQuayLai1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuayLai1.setText("Quay lại");
        btnQuayLai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLai1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tháng");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ngày sử dụng nhiều nhất");

        jLabel3.setText("Cách hạn mức");

        txtCachHanMuc.setEditable(false);

        tblChiTieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblChiTieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã giao dịch", "Ngày giao dịch", "Lượng tiền"
            }
        ));
        tblChiTieu.setRowHeight(22);
        jScrollPane1.setViewportView(tblChiTieu);

        jLabel4.setText("Tổng tiền đã chi");

        txtTongTien.setEditable(false);

        btnChiTiet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        dateNgaySDNhieuNhat.setEnabled(false);

        cbbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChiTieuLayout = new javax.swing.GroupLayout(panelChiTieu);
        panelChiTieu.setLayout(panelChiTieuLayout);
        panelChiTieuLayout.setHorizontalGroup(
            panelChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTieuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309)
                .addComponent(btnQuayLai1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelChiTieuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(dateNgaySDNhieuNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelChiTieuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtCachHanMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelChiTieuLayout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelChiTieuLayout.setVerticalGroup(
            panelChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTieuLayout.createSequentialGroup()
                .addGroup(panelChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuayLai1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelChiTieuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(panelChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelChiTieuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dateNgaySDNhieuNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelChiTieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCachHanMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabpanel.addTab("Thống kê chi tiêu", panelChiTieu);

        btnQuayLai2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuayLai2.setText("Quay lại");
        btnQuayLai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLai2ActionPerformed(evt);
            }
        });

        tblTieuDung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblTieuDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên tiêu dùng", "Số lượng", "Thành tiền"
            }
        ));
        tblTieuDung.setRowHeight(22);
        jScrollPane2.setViewportView(tblTieuDung);

        javax.swing.GroupLayout panelTieuDungLayout = new javax.swing.GroupLayout(panelTieuDung);
        panelTieuDung.setLayout(panelTieuDungLayout);
        panelTieuDungLayout.setHorizontalGroup(
            panelTieuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTieuDungLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuayLai2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        panelTieuDungLayout.setVerticalGroup(
            panelTieuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTieuDungLayout.createSequentialGroup()
                .addComponent(btnQuayLai2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabpanel.addTab("Chi tiết giao dịch", panelTieuDung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cbbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThangActionPerformed
        // TODO add your handling code here:
        tblModelChiTieu.setRowCount(0);
        ChiTieuBLL chiTieuBll = new ChiTieuBLL();
        String[]date = this.cbbThang.getSelectedItem().toString().split("/");
        arrChiTieuThang = chiTieuBll.getAllChiTieuByMonthUser(Integer.parseInt(date[0]), Integer.parseInt(date[1]), tenDangNhap);
        
        
        ChiTieuDTO chitieu = new ChiTieuDTO();
        ArrayList<String> arrMaChiTieu = new ArrayList<String>();
        double tongTienDaChi = 0;
        double luongTienMax = 0;
        for(int i=0; i<arrChiTieuThang.size();i++){
            chitieu = arrChiTieuThang.get(i);
            if(!arrMaChiTieu.contains(chitieu.getMaChiTieu())){
                String machitieu = chitieu.getMaChiTieu();
                arrMaChiTieu.add(machitieu);
                
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String ngaygiaodich = sdf.format(chitieu.getNgayChi());
                
                
                String luongtien = dinhDangTienTe(chitieu.getLuongTien());
                tongTienDaChi+=chitieu.getLuongTien();
                if(luongTienMax<chitieu.getLuongTien()){
                    luongTienMax = chitieu.getLuongTien();
                    dateNgaySDNhieuNhat.setDate(chitieu.getNgayChi());
                }
                Object[] row = {machitieu, ngaygiaodich, luongtien};
                tblModelChiTieu.addRow(row);
            }  
        }
        txtTongTien.setText(dinhDangTienTe(tongTienDaChi));
        tblChiTieu.setModel(tblModelChiTieu);
        GioiHanChiTieuBLL ghctBll = new GioiHanChiTieuBLL();
        GioiHanChiTieuDTO ghct = ghctBll.getGioiHanChiTieuByTenDangNhap(tenDangNhap);
        txtCachHanMuc.setText(dinhDangTienTe(ghct.getGioiHan()-tongTienDaChi));
    }//GEN-LAST:event_cbbThangActionPerformed

    private void btnQuayLai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLai1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnQuayLai1ActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        // TODO add your handling code here:
        tblModelTieuDung.setRowCount(0);
        int indexTB = tblChiTieu.getSelectedRow();
        ArrayList<TieuDungDTO> arrTieuDung = new ArrayList<TieuDungDTO>();
        if(indexTB<tblModelChiTieu.getRowCount() && indexTB>=0){
            TieuDungBLL tieuDungBll = new TieuDungBLL();
            arrTieuDung = tieuDungBll.getAllTieuDungByMaChiTieu(tblModelChiTieu.getValueAt(indexTB, 0).toString());
        }
        TieuDungDTO tieuDung = new TieuDungDTO();
        int stt =0;
        for(int i=0; i<arrTieuDung.size(); i++){
            tieuDung = arrTieuDung.get(i);
            stt +=1;
            String tentieudung = tieuDung.getTenHangHoa();
            int soluong = tieuDung.getSoLuong();
            String thanhtien = dinhDangTienTe(tieuDung.getThanhTien());
            Object[] row = {stt, tentieudung, soluong, thanhtien};
            tblModelTieuDung.addRow(row);
        }
        tblTieuDung.setModel(tblModelTieuDung);
        tabpanel.setSelectedIndex(1);
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnQuayLai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLai2ActionPerformed
        // TODO add your handling code here:
        tabpanel.setSelectedIndex(0);
    }//GEN-LAST:event_btnQuayLai2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeChiTieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeChiTieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeChiTieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeChiTieuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeChiTieuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnQuayLai1;
    private javax.swing.JButton btnQuayLai2;
    private javax.swing.JComboBox<String> cbbThang;
    private com.toedter.calendar.JDateChooser dateNgaySDNhieuNhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelChiTieu;
    private javax.swing.JPanel panelTieuDung;
    private javax.swing.JTabbedPane tabpanel;
    private javax.swing.JTable tblChiTieu;
    private javax.swing.JTable tblTieuDung;
    private javax.swing.JTextField txtCachHanMuc;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
